let User,CustomErrorHandler;_b75‍.x([["default",()=>_b75‍.o]]);_b75‍.w("../../models",[["User",["User"],function(v){User=v}]]);_b75‍.w("../../Services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
  async getUser(req, res, next) {
    try {
      _b75‍.g.console.log(req);
      const user = await User.findOne({ _id: req.user._id });
      if (!user) {
        return next(CustomErrorHandler.notFound());
      }

      res.json(user);
    } catch (err) {
      return next(err);
    }
  },
};

_b75‍.d(userController);
